### ISSUE TITLE
SpaceTuxLibrary does not appear in CKAN 1.13.2

### ISSUE THREAD

**Issue by CaptainChemist** [linuxgurugamer/SpaceTuxLibrary#9]
I installed CKAN and refresh the mod list to make sure I have the latest and greatest. When I search for SpaceTuxLibrary, it does not appear to be listed. I'm using the Mac version of KSP 1.12.5.3190. I'm trying to install this so I can run the waypoint manager but when I try to install the manager first, it doesn't let me install because it says SpaceTuxLibrary is missing from the list of mods. 
<img width="568" alt="Screenshot 2023-02-16 at 4 34 36 PM" src="https://user-images.githubusercontent.com/1043257/219502455-5477619d-55ce-475b-8ef5-d328fc9d0d0a.png">

How can I manually add SpaceTuxLibrary so CKAN will recognize it? Thanks!

**Comment by linuxgurugamer** [comment]
First, asking for help with a CKAN problem should have been done on the forums.  I'm only mentioning this because there are many people who are on the forums who can help, and you probably would have gotten an answer much faster than this.

Second, I updated Spacedock just now with the latest KSP version for this, so it should be ok in then next 1-2 hours.

Third, there is a way to tell CKAN to use mods listed for older versions of KSP.  In this case, it was listed for KSP 1.12.3.  I don't know how to do that using the text based version.
